### ISSUE TITLE
<C-M> default mapping breaks location list

### ISSUE THREAD

**Issue by drzel** [ckarnell/history-traverse#4]
- Populate location list
- Select loction
- Press enter

It opens in location buffer instead of parent buffer, or returns error message.

**Comment by ckarnell** [comment]
Good find - I never had this happen because I have a personal remapping for `<cr>` while in `qf` files.

I think your solution is good for now, although it makes me sad to get rid of default mappings, and I think there's also a couple superficial changes I'd make, for example, `:Back` and `:Forward` seem a little non-specific and may be a part of people's configs.

Anyway I'll try this out when I get a chance and merge it, and I really appreciate your work here!
